version: '3.8'

services:
  sogo:
    image: inverse/sogo:latest
    container_name: sogo_webmail
    restart: unless-stopped
    ports:
      - "9000:80"
    environment:
      - TZ=Asia/Dhaka
    volumes:
      - ./sogo.conf:/etc/sogo/sogo.conf:ro
      - sogo-data:/var/lib/sogo
      - sogo-logs:/var/log/sogo
    networks:
      - mailnet

networks:
  mailnet:
    driver: bridge

volumes:
  sogo-data:
  sogo-logs:
